sudo: required 
language: generic 
services: #ensure a copy of docker for travis actions 
  - docker

before_install: # some setup that needs to occur before we deploy our project
  - docker build -t docker-react -f Dockerfile.dev .

script:  # contain all the needed commands that actually run our test suite 
  - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-445589059283"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
